src/Entity/Artist.php
<?php

namespace App\Entity;

use App\Repository\ArtistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @ORM\Entity(repositoryClass=ArtistRepository::class)
 * @Vich\Uploadable
 */
class Artist
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @Vich\UploadableField(mapping="artists", fileNameProperty="portrait")
     */
    private $portraitFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $portrait;

    /**
     * @ORM\ManyToMany(targetEntity=Movie::class, mappedBy="actors")
     */
    private $hasPlayIn;

    /**
     * @ORM\OneToMany(targetEntity=Movie::class, mappedBy="director", orphanRemoval=true)
     */
    private $hasDirected;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    public function __construct()
    {
        $this->hasPlayIn = new ArrayCollection();
        $this->hasDirected = new ArrayCollection();
    }

    public function __toString(){
        return $this->getFirstname()." ".$this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPortrait(): ?string
    {
        return $this->portrait;
    }

    public function setPortrait(?string $portrait): self
    {
        $this->portrait = $portrait;

        return $this;
    }

    /**
     * @return Collection|Movie[]
     */
    public function getActorMovies(): Collection
    {
        return $this->hasPlayIn;
    }

    public function addActorMovie(Movie $hasPlayIn): self
    {
        if (!$this->hasPlayIn->contains($hasPlayIn)) {
            $this->hasPlayIn[] = $hasPlayIn;
        }
        return $this;
    }

    public function removeActorMovie(Movie $hasPlayIn): self
    {
        $this->hasPlayIn->removeElement($hasPlayIn);

        return $this;
    }

    /**
     * @return Collection|Movie[]
     */
    public function getHasDirected(): Collection
    {
        return $this->hasDirected;
    }

    public function addHasDirected(Movie $hasDirected): self
    {
        if (!$this->hasDirected->contains($hasDirected)) {
            $this->hasDirected[] = $hasDirected;
            $hasDirected->setDirector($this);
        }

        return $this;
    }

    public function removeHasDirected(Movie $hasDirected): self
    {
        if ($this->hasDirected->removeElement($hasDirected)) {
            // set the owning side to null (unless already changed)
            if ($hasDirected->getDirector() === $this) {
                $hasDirected->setDirector(null);
            }
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
 
    public function setPortraitFile(?File $portraitFile=null): void    
    {
        $this->portraitFile=$portraitFile;
        if (null!==$portraitFile) {
            $this->updatedAt=new\DateTimeImmutable();
        }
    }

    public function getPortraitFile(){
        return $this->portraitFile;
    }
}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\MovieRepository;
use App\Entity\Movie;
use App\Entity\Artist;

class FrontController extends AbstractController
{
    /**
     * @Route("/", name="index_front")
     */
    public function index( MovieRepository $movieRepo): Response
    {
        return $this->render('front/index.html.twig', [
            'movies' => $movieRepo->findAll(),
        ]);
    }
    
    /**
     * @Route("/film/{id}", name="movie_front")
     */
    public function movie( Movie $movie): Response
    {
        return $this->render('front/movie.html.twig', [
            'movie' => $movie,
        ]);
    }

    /**
     * @Route("/artiste/{id}", name="artist_front")
     */
    public function artist( Artist $artist): Response
    {
        return $this->render('front/artist.html.twig', [
            'artist' => $artist,
        ]);
    }
}

templates/front/artist.html.twig
{% extends "front.html.twig" %}
{% block main %}

    <h1>{{ artist }}</h1>
    
    <img src="{{ asset("images/artists/"~artist.portrait )}}" alt="{{ artist }}"/>
    
    {% if artist.hasDirected|length > 0 %}
        <h2>A réalisé :</h2>
        <div class="liste_vignettes">
        {% for movie in artist.hasDirected %}
            <div class="vignette">
                <a href="{{ path("movie_front", {'id':movie.id})}}">
                    <img src="{{ asset("images/posters/"~movie.poster )}}" alt="{{ movie.title}}" title="{{ movie.title}}" />
                </a> 
            </div>
        {% endfor %}
        </div>
    {% endif %}
    
    {% if artist.actorMovies|length > 0 %}
        <h2>A joué dans :</h2>
        <div class="liste_vignettes">
        {% for movie in artist.actorMovies %}
            <div class="vignette">
                <a href="{{ path("movie_front", {'id':movie.id})}}">
                    <img src="{{ asset("images/posters/"~movie.poster )}}" alt="{{ movie.title}}" title="{{ movie.title}}" />
                </a> 
            </div>
        {% endfor %}
        </div>
    {% endif %}
{% endblock %}

templates/front/index.html.twig
{% extends 'front.html.twig' %}

{% block title %}IMDB bis{% endblock %}

{% block main %}

    <h1>Tous les films</h1>
    <div class="liste_vignettes">
    {% for movie in movies %}
        <div class="vignette">
            <a href="{{ path("movie_front", {'id':movie.id})}}">
                <img src="{{ asset("images/posters/"~movie.poster )}}" alt="{{ movie.title}}" title="{{ movie.title}}" />
            </a> 
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

templates/front/movie.html.twig
{% extends "front.html.twig" %}
{% block main %}

    <h1>{{ movie.title }}</h1>
    
    <div class="content">
        <img src="{{ asset("images/posters/"~movie.poster)}}" alt="{{ movie.title}}" />
        <p>Réalisateur : <a href="{{ path("artist_front", {"id":movie.director.id})}}">{{ movie.director }}</a></p>
        <p>{{ movie.description}}</p>
    </div>
    
    <h2>Casting</h2>
    <div class="liste_vignettes">
        {% for actor in movie.actors %}
            <div class="vignette">
                <a href="{{ path("artist_front", {"id":actor.id})}}">
                    <div>
                        <img src="{{ asset("images/artists/"~actor.portrait )}}" alt="{{ actor }}" />
                    </div>
                    <p>{{ actor }}</p>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}